config/routes.rb
AwesomeConnect::Application.routes.draw do
  
  resources :identities

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  resources :appdotnet_socials
  resources :facebook_socials
  resources :twitter_socials
  resources :landings
  devise_for :users

  root :to => 'twitter_socials#index'
  

end

app/models/landing.rb
class Landing < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  # GET /landings
  # GET /landings.json
  
  before_filter :authenticate_user!
  
  def index
    @landings = Landing.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landings }
    end
  end

  # GET /landings/1
  # GET /landings/1.json
  def show
    @landing = Landing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landing }
    end
  end

  # GET /landings/new
  # GET /landings/new.json
  def new
    @landing = Landing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landing }
    end
  end

  # GET /landings/1/edit
  def edit
    @landing = Landing.find(params[:id])
  end

  # POST /landings
  # POST /landings.json
  def create
    @landing = Landing.new(params[:landing])

    respond_to do |format|
      if @landing.save
        format.html { redirect_to @landing, notice: 'Landing was successfully created.' }
        format.json { render json: @landing, status: :created, location: @landing }
      else
        format.html { render action: "new" }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landings/1
  # PUT /landings/1.json
  def update
    @landing = Landing.find(params[:id])

    respond_to do |format|
      if @landing.update_attributes(params[:landing])
        format.html { redirect_to @landing, notice: 'Landing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landings/1
  # DELETE /landings/1.json
  def destroy
    @landing = Landing.find(params[:id])
    @landing.destroy

    respond_to do |format|
      format.html { redirect_to landings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_form.html.erb
<%= form_for @landing, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                landings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/landings/edit.html.erb
<h1>Editing landing</h1>

<%= render 'form' %>

<%= link_to 'Show', @landing %> |
<%= link_to 'Back', landings_path %>

app/views/landings/index.html.erb
<h1>Listing landings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landings.each do |landing| %>
  <tr>
    <td><%= link_to 'Show', landing %></td>
    <td><%= link_to 'Edit', edit_landing_path(landing) %></td>
    <td><%= link_to 'Destroy', landing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landing', new_landing_path %>

app/views/landings/new.html.erb
<h1>New landing</h1>

<%= render 'form' %>

<%= link_to 'Back', landings_path %>

app/views/landings/show.html.erb
<%- model_class = Landing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              landings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_landing_path(@landing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              landing_path(@landing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>