config/routes.rb
AwesomeConnect::Application.routes.draw do
  
  resources :identities

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  resources :appdotnet_socials
  resources :facebook_socials
  resources :twitter_socials
  resources :landings
  devise_for :users

  root :to => 'twitter_socials#index'
  

end

app/models/appdotnet_social.rb
class AppdotnetSocial < ActiveRecord::Base
  
  belongs_to :identity
  
  include HTTParty
   base_uri 'alpha-api.app.net'
   
  attr_accessible :uid, :username
  


#  def timeline(which=:friends, options={})
#    options.merge!({:basic_auth => @auth})
#    self.class.get("/statuses/#{which}_timeline.json", options)
#  end
  
  def token(which=:friends, options={})
    options.merge!({:basic_auth => @auth})
    self.class.get("/stream/0/token?access_token=#{self.identity.oauth_token}", options)
  end
  
  def user(which=:friends, options={})
    options.merge!({:basic_auth => @auth})
    self.class.get("/stream/0/users/#{uid}?access_token=#{self.identity.oauth_token}", options)
  end

  def posts(which=:friends, options={})
    options.merge!({:basic_auth => @auth})
    self.class.get("/stream/0/posts/#{uid}?access_token=#{self.identity.oauth_token}", options)
  end
  
  def following(which=:friends, options={})
    options.merge!({:basic_auth => @auth})
    self.class.get("/stream/0/users/#{uid}/following?access_token=#{self.identity.oauth_token}", options)
  end

end

app/controllers/appdotnet_socials_controller.rb
class AppdotnetSocialsController < ApplicationController
  # GET /appdotnet_socials
  # GET /appdotnet_socials.json
  
  require 'open-uri'
  before_filter :authenticate_user!
  
  def index
    @appdotnet_socials = AppdotnetSocial.all
    if @appdotnet_socials.nil?
      binding.pry
      @user = @appdotnet_socials.first.user
      @token = @appdotnet_socials.first.token
    end

      # id = current_user.identities.find_by_provider('appdotnet')
      # @globalfeeds = JSON.parse(open("https://alpha-api.app.net/stream/0/posts/stream/global").read).first    
      # @post = JSON.parse(open("https://alpha-api.app.net/stream/0/posts/#{id.uid.to_s}?access_token=#{id.oauth_token}").read)    
      # @me = JSON.parse(open("https://alpha-api.app.net/stream/0/users/#{id.uid.to_s}?access_token=#{id.oauth_token}").read)   
      # @following  = JSON.parse(open("https://alpha-api.app.net/stream/0/users/#{id.uid.to_s}/following?access_token=#{id.oauth_token}").read)   
      # @token  = JSON.parse(open("https://alpha-api.app.net/stream/0/token?access_token=#{id.oauth_token}").read)       
    
#    binding.pry   

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: [@appdotnet_socials, @user, @token]}
    end
  end

  # GET /appdotnet_socials/1
  # GET /appdotnet_socials/1.json
  def show
    @appdotnet_social = AppdotnetSocial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appdotnet_social }
    end
  end

  # GET /appdotnet_socials/new
  # GET /appdotnet_socials/new.json
  def new
    @appdotnet_social = AppdotnetSocial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appdotnet_social }
    end
  end

  # GET /appdotnet_socials/1/edit
  def edit
    @appdotnet_social = AppdotnetSocial.find(params[:id])
  end

  # POST /appdotnet_socials
  # POST /appdotnet_socials.json
  def create
    @appdotnet_social = AppdotnetSocial.new(params[:appdotnet_social])

    respond_to do |format|
      if @appdotnet_social.save
        format.html { redirect_to @appdotnet_social, notice: 'Appdotnet social was successfully created.' }
        format.json { render json: @appdotnet_social, status: :created, location: @appdotnet_social }
      else
        format.html { render action: "new" }
        format.json { render json: @appdotnet_social.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appdotnet_socials/1
  # PUT /appdotnet_socials/1.json
  def update
    @appdotnet_social = AppdotnetSocial.find(params[:id])

    respond_to do |format|
      if @appdotnet_social.update_attributes(params[:appdotnet_social])
        format.html { redirect_to @appdotnet_social, notice: 'Appdotnet social was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appdotnet_social.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appdotnet_socials/1
  # DELETE /appdotnet_socials/1.json
  def destroy
    @appdotnet_social = AppdotnetSocial.find(params[:id])
    @appdotnet_social.destroy

    respond_to do |format|
      format.html { redirect_to appdotnet_socials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appdotnet_socials_helper.rb
module AppdotnetSocialsHelper
end

app/views/appdotnet_socials/_form.html.erb
<%= form_for @appdotnet_social, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :uid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                appdotnet_socials_path, :class => 'btn' %>
  </div>
<% end %>

app/views/appdotnet_socials/edit.html.erb
<%- model_class = AppdotnetSocial -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appdotnet_socials/index.html.erb
<%- model_class = AppdotnetSocial -%>
<div class="page-header">
  <h1><%=t '.title', :default => "App.net" %></h1>
</div>

<div id="container">
  <div id="user_nav>">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %> locally</strong>.<br /><br />
              
      <% if current_user.identities %>
          <p><%=current_user.email %> has oauth identities for the following providers</p>
        <% current_user.identities.each do |identity| %>
          <ul><br />
           <blockquote><strong>provider:</strong>  <%= identity.provider %></li><br />
           <strong>user:</strong>  <%= identity.name %></li>
          </blockquote>
          </ul>
        <% end %>
              <%= link_to "Sign in with App.net", user_omniauth_authorize_path(:appdotnet) %>  
      <% else %>
              <%= link_to "Sign in with App.net", user_omniauth_authorize_path(:appdotnet) %>   
      <% end %>
      
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %> | 
      <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>                               
    <% end %>
  </div>
</div>

<div id="globalfeeds" data-globalfeeds="<%= render(template: "appdotnet_socials/index.json.rabl")%>">


<%- model_class = Landing -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Your details" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:uid) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @appdotnet_socials.each do |social| %>
      <tr>
        <td><%= link_to social.uid, landing_path(social) %></td>
        <td><%= social.username %></td>
        <td><%= social.identity.provider %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_appdotnet_social_path(social), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      appdotnet_social_path(social),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appdotnet_socials/new.html.erb
<%- model_class = AppdotnetSocial -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appdotnet_socials/show.html.erb
<%- model_class = AppdotnetSocial -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @appdotnet_social.uid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @appdotnet_social.username %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              appdotnet_socials_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_appdotnet_social_path(@appdotnet_social), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              appdotnet_social_path(@appdotnet_social),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>