config/routes.rb
AwesomeConnect::Application.routes.draw do
  
  resources :identities

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  resources :appdotnet_socials
  resources :facebook_socials
  resources :twitter_socials
  resources :landings
  devise_for :users

  root :to => 'twitter_socials#index'
  

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  has_many :appdotnet_social
  
  attr_accessible :uid, :provider, :name, :oauth_token, :oauth_expires_at
  
  def self.find_with_omniauth(auth)
    find_by_provider_and_uid(auth['provider'], auth['uid'])
  end

  def self.create_with_omniauth(auth)
    #TwitterSocial.create(followers_count: auth["extra"]["raw_info"]["followers_count"])
    create(uid: auth['uid'], provider: auth['provider'], name: auth['info']['name'], oauth_token: auth['credentials']['token'], oauth_expires_at: auth['credentials']['expires_at'])
    
  end
  
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    
  end
  
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  # GET /identities
  # GET /identities.json
  def index
    @identities = Identity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @identities }
    end
  end

  # GET /identities/1
  # GET /identities/1.json
  def show
    @identity = Identity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @identity }
    end
  end

  # GET /identities/new
  # GET /identities/new.json
  def new
    @identity = Identity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @identity }
    end
  end

  # GET /identities/1/edit
  def edit
    @identity = Identity.find(params[:id])
  end

  # POST /identities
  # POST /identities.json
  def create
    @identity = Identity.new(params[:identity])

    respond_to do |format|
      if @identity.save
        format.html { redirect_to @identity, notice: 'Identity was successfully created.' }
        format.json { render json: @identity, status: :created, location: @identity }
      else
        format.html { render action: "new" }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /identities/1
  # PUT /identities/1.json
  def update
    @identity = Identity.find(params[:id])

    respond_to do |format|
      if @identity.update_attributes(params[:identity])
        format.html { redirect_to @identity, notice: 'Identity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identities/1
  # DELETE /identities/1.json
  def destroy
    @identity = Identity.find(params[:id])
    @identity.destroy

    respond_to do |format|
      format.html { redirect_to identities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/_form.html.erb
<%= form_for(@identity) do |f| %>
  <% if @identity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this identity from being saved:</h2>

      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/identities/edit.html.erb
<h1>Editing identity</h1>

<%= render 'form' %>

<%= link_to 'Show', @identity %> |
<%= link_to 'Back', identities_path %>

app/views/identities/index.html.erb
<h1>Listing identities</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @identities.each do |identity| %>
  <tr>
    <td><%= identity.provider %></td>
    <td><%= identity.uid %></td>
    <td><%= link_to 'Show', identity %></td>
    <td><%= link_to 'Edit', edit_identity_path(identity) %></td>
    <td><%= link_to 'Destroy', identity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Identity', new_identity_path %>

app/views/identities/new.html.erb
<h1>New identity</h1>

<%= render 'form' %>

<%= link_to 'Back', identities_path %>

app/views/identities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @identity.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @identity.uid %>
</p>


<%= link_to 'Edit', edit_identity_path(@identity) %> |
<%= link_to 'Back', identities_path %>